Take ["Control", "ScopeReady"], (Control)->
  Control.button name:"Start", click:()=> console.log "start"
  Control.button name:"Reset", click:()=> console.log "reset"
  Control.button name:"Start", click:()=> console.log "start"
  Control.button name:"Reset", click:()=> console.log "reset"
  Control.button name:"Start", click:()=> console.log "start"
  Control.button name:"Reset", click:()=> console.log "reset"
  Control.button name:"Start", click:()=> console.log "start"
  Control.button name:"Reset", click:()=> console.log "reset"
  Control.button name:"Start", click:()=> console.log "start"
  Control.button name:"Reset", click:()=> console.log "reset"
