Take ["Control", "ScopeReady"], (Control)->
  Control.button name:"S", click:()=> console.log "start"
  Control.button name:"SS", click:()=> console.log "reset"
  Control.button name:"SSS", click:()=> console.log "start"
  Control.button name:"SSSS", click:()=> console.log "reset"
  Control.button name:"SSSSS", click:()=> console.log "start"
  Control.button name:"SSSSSS", click:()=> console.log "reset"
  Control.button name:"SSSSSSS", click:()=> console.log "start"
  Control.button name:"S", click:()=> console.log "reset"
  Control.button name:"SSSSSSSS", click:()=> console.log "reset"
  Control.button name:"SSSSSSSSS", click:()=> console.log "start"
  Control.button name:"SSSSSSSSSS", click:()=> console.log "reset"
  Control.button name:"SSSSSSSSSSS", click:()=> console.log "reset"
  Control.button name:"SSSSSSSSSSSS", click:()=> console.log "reset"
  Control.button name:"SSSSSSSSSSSS", click:()=> console.log "reset"
  Control.button name:"S", click:()=> console.log "reset"
